use serde::{Deserialize, Serialize};

/// MT4/MT5のタイプ
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "UPPERCASE")]
pub enum MtType {
    MT4,
    MT5,
}

/// アーキテクチャビット数
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Architecture {
    #[serde(rename = "32-bit")]
    Bit32,
    #[serde(rename = "64-bit")]
    Bit64,
}

/// インストールされたコンポーネント（実行に必要なもののみ）
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct InstalledComponents {
    pub dll: bool,
    pub master_ea: bool,
    pub slave_ea: bool,
}

/// EA用ポート設定（sankey_copier.iniから読み込み）
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct EaPortConfig {
    pub receiver_port: u16,
    pub publisher_port: u16,
    pub config_sender_port: u16,
}

impl EaPortConfig {
    /// INIファイル内容をパースしてEaPortConfigを生成
    pub fn from_ini_content(content: &str) -> Option<Self> {
        let mut config = EaPortConfig::default();
        let mut found_section = false;

        for line in content.lines() {
            let line = line.trim();

            // セクションチェック
            if line.eq_ignore_ascii_case("[ZeroMQ]") {
                found_section = true;
                continue;
            }

            // 別のセクションが始まったら終了
            if line.starts_with('[') && found_section {
                break;
            }

            // ZeroMQセクション内のキー=値をパース
            if found_section && !line.starts_with('#') && !line.is_empty() {
                if let Some((key, value)) = line.split_once('=') {
                    let key = key.trim();
                    let value = value.trim();

                    if let Ok(port) = value.parse::<u16>() {
                        match key {
                            "ReceiverPort" => config.receiver_port = port,
                            "PublisherPort" => config.publisher_port = port,
                            "ConfigSenderPort" => config.config_sender_port = port,
                            _ => {}
                        }
                    }
                }
            }
        }

        // 有効なポート設定が見つかった場合のみ返す
        if config.receiver_port > 0 || config.publisher_port > 0 || config.config_sender_port > 0 {
            Some(config)
        } else {
            None
        }
    }
}

/// MT4/MT5インストール情報
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MtInstallation {
    pub id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub mt_type: MtType,
    pub platform: Architecture,
    pub path: String,
    pub executable: String,
    pub version: Option<String>, // DLLバージョン = クライアントバージョン
    pub components: InstalledComponents,
    /// EA設定ファイル（sankey_copier.ini）のポート設定
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port_config: Option<EaPortConfig>,
    /// サーバーの設定とEAのポート設定が一致しない場合true
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port_mismatch: Option<bool>,
}

/// 検出サマリー
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionSummary {
    pub total_found: usize,
}

/// MT4/MT5検出結果のレスポンス
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MtInstallationsResponse {
    pub success: bool,
    pub data: Vec<MtInstallation>,
    pub detection_summary: DetectionSummary,
    /// サーバーが使用中のポート設定
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_ports: Option<EaPortConfig>,
}

impl MtInstallation {
    /// インストールIDを生成
    #[cfg_attr(not(windows), allow(dead_code))]
    pub fn generate_id(mt_type: &MtType, path: &str) -> String {
        // パスから識別可能なIDを生成
        let mut path_hash = path.to_lowercase().replace(['\\', '/', ' ', ':'], "-");

        // 連続したハイフンを単一のハイフンに置き換え
        while path_hash.contains("--") {
            path_hash = path_hash.replace("--", "-");
        }

        // 前後のハイフンを削除
        let path_hash = path_hash.trim_matches('-').to_string();

        let type_prefix = match mt_type {
            MtType::MT4 => "mt4",
            MtType::MT5 => "mt5",
        };

        format!("{}-{}", type_prefix, path_hash)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_id() {
        let id = MtInstallation::generate_id(&MtType::MT4, "D:\\Trading\\IC Markets MT4");
        assert_eq!(id, "mt4-d-trading-ic-markets-mt4");

        let id = MtInstallation::generate_id(&MtType::MT5, "C:\\Program Files\\XM MetaTrader 5");
        assert_eq!(id, "mt5-c-program-files-xm-metatrader-5");
    }

    #[test]
    fn test_ea_port_config_from_ini_content() {
        let ini_content = r#"# SANKEY Copier Configuration
# Auto-generated by relay-server installer

[ZeroMQ]
ReceiverPort=15555
PublisherPort=15556
ConfigSenderPort=15557
"#;

        let config = EaPortConfig::from_ini_content(ini_content).unwrap();
        assert_eq!(config.receiver_port, 15555);
        assert_eq!(config.publisher_port, 15556);
        assert_eq!(config.config_sender_port, 15557);
    }

    #[test]
    fn test_ea_port_config_from_ini_content_with_spaces() {
        let ini_content = r#"[ZeroMQ]
ReceiverPort = 5555
PublisherPort = 5556
ConfigSenderPort = 5557
"#;

        let config = EaPortConfig::from_ini_content(ini_content).unwrap();
        assert_eq!(config.receiver_port, 5555);
        assert_eq!(config.publisher_port, 5556);
        assert_eq!(config.config_sender_port, 5557);
    }

    #[test]
    fn test_ea_port_config_from_ini_content_empty() {
        let ini_content = "";
        let config = EaPortConfig::from_ini_content(ini_content);
        assert!(config.is_none());
    }

    #[test]
    fn test_ea_port_config_from_ini_content_no_zeromq_section() {
        let ini_content = r#"[Other]
SomeKey=SomeValue
"#;

        let config = EaPortConfig::from_ini_content(ini_content);
        assert!(config.is_none());
    }

    #[test]
    fn test_ea_port_config_from_ini_content_partial() {
        let ini_content = r#"[ZeroMQ]
ReceiverPort=12345
"#;

        let config = EaPortConfig::from_ini_content(ini_content).unwrap();
        assert_eq!(config.receiver_port, 12345);
        assert_eq!(config.publisher_port, 0);
        assert_eq!(config.config_sender_port, 0);
    }
}
